services:
  react:
    build:
      context: .
      dockerfile: ./compose/local/Dockerfile
    image: taskminder_local_react
    container_name: taskminder_local_react
    volumes:
      - .:/app:z
    ports:
      - 5173:5173
